### ISSUE TITLE
How to input video URL

### ISSUE THREAD

**Issue by blackcodersec** [tiemi/automatic-blog-post#3]
I don't know what's my wrong. could you help me!
![image](https://user-images.githubusercontent.com/72689232/162145334-cfdd7400-5908-4d60-849d-5e322b507806.png)

**Comment by tiemi** [comment]
@blackcodersec , can you pull the main branch again and check if it's working now? I've created an empty init file to guarantee that it will be treated as a module

**Comment by blackcodersec** [comment]
I pull the main branch, but same issue. not working. is my command right?

![image](https://user-images.githubusercontent.com/72689232/162191735-733ca2cf-641f-4c3e-b614-e1c20f3fc2f9.png)

**Comment by blackcodersec** [comment]
@tiemi hello could you give me solution?

**Comment by tiemi** [comment]
@blackcodersec , I've updated the requirements because it was missing one package (the keyphrase_vectorizers). Also, I've updated the description of the read.me file giving an example of the video URL and how to create a virtual environment with Conda. Thank you for letting me know. Can you check one last time?

**Comment by tiemi** [comment]
The video that you are trying to convert to a blog post doesn't have audio, just an instrumental soundtrack. So, I would recommend you try another tutorial. For example:  https://www.youtube.com/watch?v=kibx5BR6trA&ab_channel=Deepgram
